name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set-tag.outputs.tag }}

    steps:
    - uses: actions/checkout@v4

    - name: Set image tag
      id: set-tag
      run: echo "tag=$(date +%s)" >> $GITHUB_OUTPUT

    - name: Log in to Docker Hub
      run: echo "Gandr0108*" | docker login -u "connie888" --password-stdin

    - name: Build and Tag Docker Image
      run: |
        IMAGE_NAME=mnist_classifier
        IMAGE_TAG=${{ steps.set-tag.outputs.tag }}
        docker build . -f Dockerfile2 -t $IMAGE_NAME:$IMAGE_TAG
        docker tag $IMAGE_NAME:$IMAGE_TAG connie888/$IMAGE_NAME:$IMAGE_TAG
        docker save connie888/$IMAGE_NAME:$IMAGE_TAG | gzip > image.tar.gz

    - name: Upload Docker Image Artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-image
        path: image.tar.gz

  push:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Download Docker Image Artifact
      uses: actions/download-artifact@v4
      with:
        name: docker-image

    - name: Load Docker Image
      run: gunzip -c image.tar.gz | docker load

    - name: Log in to Docker Hub
      run: echo "Gandr0108*" | docker login -u "connie888" --password-stdin

    - name: Push Docker Image
      run: |
        IMAGE_NAME=mnist_classifier
        IMAGE_TAG=${{ needs.build.outputs.image_tag }}
        docker push connie888/$IMAGE_NAME:$IMAGE_TAG
