name: Docker Image CI

on:
  push:
    branches: [ "test1" ]
  pull_request:
    branches: [ "test1" ]

jobs:
  build1:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set-tag.outputs.tag }}

    steps:
    - uses: actions/checkout@v4

    - name: Set image tag
      id: set-tag
      run: echo "tag=build1-$(date +%s)" >> $GITHUB_OUTPUT

    - name: Log in to Docker Hub
      run: echo "Gandr0108*" | docker login -u "connie888" --password-stdin

    - name: Build and Tag Docker Image
      run: |
        IMAGE_NAME=mnist_classifier
        IMAGE_TAG=${{ steps.set-tag.outputs.tag }}
        docker build . -f Dockerfile2 -t $IMAGE_NAME:$IMAGE_TAG
        docker tag $IMAGE_NAME:$IMAGE_TAG connie888/$IMAGE_NAME:$IMAGE_TAG
        docker save connie888/$IMAGE_NAME:$IMAGE_TAG | gzip > build1.tar.gz

    - name: Upload Docker Image Artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-image-build1
        path: build1.tar.gz

  build2:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set-tag.outputs.tag }}

    steps:
    - uses: actions/checkout@v4

    - name: Set image tag
      id: set-tag
      run: echo "tag=build2-$(date +%s)" >> $GITHUB_OUTPUT

    - name: Log in to Docker Hub
      run: echo "Gandr0108*" | docker login -u "connie888" --password-stdin

    - name: Build and Tag Docker Image
      run: |
        IMAGE_NAME=mnist_classifier
        IMAGE_TAG=${{ steps.set-tag.outputs.tag }}
        docker build . -f Dockerfile2 -t $IMAGE_NAME:$IMAGE_TAG
        docker tag $IMAGE_NAME:$IMAGE_TAG connie888/$IMAGE_NAME:$IMAGE_TAG
        docker save connie888/$IMAGE_NAME:$IMAGE_TAG | gzip > build2.tar.gz

    - name: Upload Docker Image Artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-image-build2
        path: build2.tar.gz

  push:
    needs: [build1, build2]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Download Build1 Image
      uses: actions/download-artifact@v4
      with:
        name: docker-image-build1

    - name: Download Build2 Image
      uses: actions/download-artifact@v4
      with:
        name: docker-image-build2

    - name: Load Docker Images
      run: |
        gunzip -c build1.tar.gz | docker load
        gunzip -c build2.tar.gz | docker load

    - name: Log in to Docker Hub
      run: echo "Gandr0108*" | docker login -u "connie888" --password-stdin

    - name: Push Docker Images
      run: |
        IMAGE_NAME=mnist_classifier
        TAG1=${{ needs.build1.outputs.image_tag }}
        TAG2=${{ needs.build2.outputs.image_tag }}
        docker push connie888/$IMAGE_NAME:$TAG1
        docker push connie888/$IMAGE_NAME:$TAG2
